=== DendraScience/dendra-web-api/schema/datastream.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "datastream.json",
  "title": "Datastream",
  "description": "A continuous series of datapoints indexed in time order.",
  "type": "object",
  "definitions": {
    "_id": {
      "$ref": "types.json#/definitions/datastreamId"
    },
    "attributes": {
      "$ref": "types.json#/definitions/datastreamAttributes"
    },
    "attributes_info": {
      "type": "object",
      "description": "System generated information about this datastream's attributes",
      "example": {
        "sort": {
          "value1": 10,
          "value2": 0
        },
        "text": "10 m",
        "unit_term": {
          "abbreviation": "m",
          "label": "Meter",
          "scheme_id": "dt",
          "vocabulary_id": "dt-unit",
          "vocabulary_label": "Unit",
          "vocabulary_type": "unit"
        }
      }
    },
    "convertible_to_uoms": {
      "type": "array",
      "description": "One or more populated unit of measurement objects based on the convertible to uom identifiers",
      "minItems": 1,
      "items": {
        "type": "object",
        "example": {}
      }
    },
    "datapoints_config": {
      "type": "array",
      "description": "Service configuration used for fetching datapoints",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "connection": {
            "type": "string",
            "example": "legacy"
          },
          "begins_at": {
            "$ref": "types.json#/definitions/isoDate"
          },
          "ends_before": {
            "$ref": "types.json#/definitions/isoDate"
          },
          "params": {
            "type": "object",
            "example": {
              "query": {
                "datastream_id": 3090,
                "time_adjust": -28800
              }
            }
          },
          "path": {
            "type": "string",
            "example": "/datavalues-ucnrs"
          }
        },
        "required": [
          "params",
          "path"
        ],
        "additionalProperties": false
      }
    },
    "derivation_description": {
      "type": "string",
      "example": "Calculated server-side based on the Celsius datastream."
    },
    "derived_from_datastream_ids": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "types.json#/definitions/datastreamId",
        "example": "592f155746a1b867a114e021"
      }
    },
    "description": {
      "$ref": "types.json#/definitions/description",
      "example": "Blue Oak Ranch average air temperature in degree Fahrenheit at 10 meter height."
    },
    "enabled": {
      "type": "boolean",
      "description": "Whether this datastream is enabled (shown) in any user interface",
      "example": true
    },
    "external_refs": {
      "$ref": "types.json#/definitions/externalRefs",
      "example": [
        {
          "identifier": "3090",
          "type": "odm.datastreams.datastreamid"
        },
        {
          "identifier": "334",
          "type": "odm.stations.stationid",
          "url": "http://sensor.berkeley.edu/index_ucnrs.html"
        }
      ]
    },
    "geo": {
      "$ref": "types.json#/definitions/geoPoint"
    },
    "hashes": {
      "$ref": "types.json#/definitions/hashes"
    },
    "members": {
      "$ref": "types.json#/definitions/members"
    },
    "name": {
      "type": "string",
      "example": "Blue Oak Ranch Avg Air Temp F 10 m"
    },
    "organization_id": {
      "$ref": "types.json#/definitions/organizationId",
      "description": "The organization to which this datastream belongs"
    },
    "preferred_uom_ids": {
      "type": "array",
      "description": "One or more preferred unit of measurements for display",
      "minItems": 1,
      "items": {
        "$ref": "types.json#/definitions/uomId"
      }
    },
    "preferred_uoms": {
      "type": "array",
      "description": "One or more populated preferred unit of measurement objects based on the preferred uom identifiers",
      "minItems": 1,
      "items": {
        "type": "object",
        "example": {}
      }
    },
    "source": {
      "$ref": "types.json#/definitions/datastreamSource"
    },
    "source_type": {
      "type": "string",
      "description": "The specific type of data producing entity",
      "example": "sensor",
      "enum": [
        "sensor",
        "service",
        "procedure"
      ]
    },
    "state": {
      "type": "string",
      "description": "The current functional state of this datastream",
      "example": "ready",
      "const": "ready"
    },
    "station_id": {
      "$ref": "types.json#/definitions/stationId",
      "description": "A station that is the source of this datastream"
    },
    "tags": {
      "$ref": "types.json#/definitions/datastreamTags"
    },
    "tags_info": {
      "type": "object",
      "description": "System generated information about this datastream's tags",
      "example": {
        "resolved_terms": [
          {
            "label": "Average",
            "scheme_id": "ds",
            "vocabulary_id": "ds-aggregate",
            "vocabulary_label": "Aggregate",
            "vocabulary_type": "class"
          },
          {
            "abbreviation": "degF",
            "label": "DegreeFahrenheit",
            "scheme_id": "dt",
            "vocabulary_id": "dt-unit",
            "vocabulary_label": "Unit",
            "vocabulary_type": "unit"
          }
        ],
        "unit_tag": "dt_Unit_DegreeFahrenheit",
        "unit_term": {
          "abbreviation": "degF",
          "label": "DegreeFahrenheit",
          "scheme_id": "dt",
          "vocabulary_id": "dt-unit",
          "vocabulary_label": "Unit",
          "vocabulary_type": "unit"
        },
        "scheme_refs": [
          {"_id": "ds", "tag_count": 3},
          {"_id": "dt", "tag_count": 1}
        ],
        "vocabulary_refs": [
          {"_id": "dt-aggregate"},
          {"_id": "ds-variable"}
        ]
      }
    },
    "thing_id": {
      "$ref": "types.json#/definitions/thingId",
      "description": "A thing that is the source of this datastream"
    },
    "uom": {
      "type": "object",
      "description": "A populated unit of measurement object based on the unit tag",
      "example": {}
    },
    "urls": {
      "$ref": "types.json#/definitions/urls",
      "description": "A list of URLs for the datastream (e.g. specifications)",
      "example": [
        {
          "label": "Wiki",
          "url": "https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature"
        }
      ]
    }
  },
  "additionalProperties": false,
  "properties": {
    "_id": {"$ref": "#/definitions/_id"},
    "created_at": {"$ref": "types.json#/definitions/createdAt"},
    "updated_at": {"$ref": "types.json#/definitions/updatedAt"},
    "attributes": {"$ref": "#/definitions/attributes"},
    "attributes_info": {"$ref": "#/definitions/attributes_info"},
    "convertible_to_uoms": {"$ref": "#/definitions/convertible_to_uoms"},
    "datapoints_config": {"$ref": "#/definitions/datapoints_config"},
    "derivation_description": {"$ref": "#/definitions/derivation_description"},
    "derived_from_datastream_ids": {"$ref": "#/definitions/derived_from_datastream_ids"},
    "description": {"$ref": "#/definitions/description"},
    "enabled": {"$ref": "#/definitions/enabled"},
    "external_refs": {"$ref": "#/definitions/external_refs"},
    "geo": {"$ref": "#/definitions/geo"},
    "hashes": {"$ref": "#/definitions/hashes"},
    "members": {"$ref": "#/definitions/members"},
    "name": {"$ref": "#/definitions/name"},
    "organization_id": {"$ref": "#/definitions/organization_id"},
    "preferred_uom_ids": {"$ref": "#/definitions/preferred_uom_ids"},
    "preferred_uoms": {"$ref": "#/definitions/preferred_uoms"},
    "source": {"$ref": "#/definitions/source"},
    "source_type": {"$ref": "#/definitions/source_type"},
    "state": {"$ref": "#/definitions/state"},
    "station_id": {"$ref": "#/definitions/station_id"},
    "tags": {"$ref": "#/definitions/tags"},
    "tags_info": {"$ref": "#/definitions/tags_info"},
    "thing_id": {"$ref": "#/definitions/thing_id"},
    "uom": {"$ref": "#/definitions/uom"},
    "urls": {"$ref": "#/definitions/urls"}
  },
  "required": [
    "enabled",
    "name"
  ],
  "links": [
    {
      "title": "Create datastream",
      "description": "Create a new datastream.",
      "rel": "self",
      "href": "datastreams",
      "method": "POST",
      "schema": {
        "type": "object",
        "properties": {
          "attributes": {"$ref": "#/definitions/attributes"},
          "datapoints_config": {"$ref": "#/definitions/datapoints_config"},
          "derivation_description": {"$ref": "#/definitions/derivation_description"},
          "derived_from_datastream_ids": {"$ref": "#/definitions/derived_from_datastream_ids"},
          "description": {"$ref": "#/definitions/description"},
          "enabled": {"$ref": "#/definitions/enabled"},
          "external_refs": {"$ref": "#/definitions/external_refs"},
          "geo": {"$ref": "#/definitions/geo"},
          "members": {"$ref": "#/definitions/members"},
          "name": {"$ref": "#/definitions/name"},
          "organization_id": {"$ref": "#/definitions/organization_id"},
          "preferred_uom_ids": {"$ref": "#/definitions/preferred_uom_ids"},
          "source": {"$ref": "#/definitions/source"},
          "source_type": {"$ref": "#/definitions/source_type"},
          "state": {"$ref": "#/definitions/state"},
          "station_id": {"$ref": "#/definitions/station_id"},
          "tags": {"$ref": "#/definitions/tags"},
          "thing_id": {"$ref": "#/definitions/thing_id"},
          "urls": {"$ref": "#/definitions/urls"}
        },
        "required": [
          "enabled",
          "name"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Update datastream",
      "description": "Update an existing datastream.",
      "rel": "self",
      "href": "datastreams/{#/definitions/_id}",
      "method": "PUT",
      "schema": {
        "type": "object",
        "properties": {
          "attributes": {"$ref": "#/definitions/attributes"},
          "datapoints_config": {"$ref": "#/definitions/datapoints_config"},
          "derivation_description": {"$ref": "#/definitions/derivation_description"},
          "derived_from_datastream_ids": {"$ref": "#/definitions/derived_from_datastream_ids"},
          "description": {"$ref": "#/definitions/description"},
          "enabled": {"$ref": "#/definitions/enabled"},
          "external_refs": {"$ref": "#/definitions/external_refs"},
          "geo": {"$ref": "#/definitions/geo"},
          "members": {"$ref": "#/definitions/members"},
          "name": {"$ref": "#/definitions/name"},
          "organization_id": {"$ref": "#/definitions/organization_id"},
          "preferred_uom_ids": {"$ref": "#/definitions/preferred_uom_ids"},
          "source": {"$ref": "#/definitions/source"},
          "source_type": {"$ref": "#/definitions/source_type"},
          "state": {"$ref": "#/definitions/state"},
          "station_id": {"$ref": "#/definitions/station_id"},
          "tags": {"$ref": "#/definitions/tags"},
          "thing_id": {"$ref": "#/definitions/thing_id"},
          "urls": {"$ref": "#/definitions/urls"}
        },
        "required": [
          "enabled",
          "name"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Remove datastream",
      "description": "Remove an existing datastream.",
      "rel": "self",
      "href": "datastreams/{#/definitions/_id}",
      "method": "DELETE",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Datastream info",
      "description": "Return a specific datastream.",
      "rel": "self",
      "href": "datastreams/{#/definitions/_id}",
      "method": "GET",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "List datastreams",
      "description": "Find one or more datastreams based on the query parameters.",
      "rel": "instances",
      "href": "datastreams",
      "method": "GET",
      "schema": {
        "$ref": "types.json#/definitions/queryParameters"
      },
      "targetSchema": {
        "allOf": [
          {"$ref": "types.json#/definitions/paginationMeta"},
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {"rel": "self"}
              }
            }
          }
        ]
      }
    },
    {
      "title": "Lookup datastreams",
      "description": "Find up to 100 datastreams based on the query parameters (ordered by _id). This endpoint evaluates the _id, source, and station_id parameters in a logical disjunction (OR). The attributes_exist and tags parameters can be added to further restrict datastreams selected by the source and station_id parameters.",
      "rel": "instances",
      "href": "datastreams/lookup",
      "method": "GET",
      "schema": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "som_id": {
                "$ref": "types.json#/definitions/somId",
                "description": "Do a fuzzy match and return a unique set of datastreams that are already in or could be converted to this system of measurement"
              }
            }
          },
          {"$ref": "types.json#/definitions/datastreamLookupParameters"}
        ]
      },
      "targetSchema": {
        "type": "array",
        "items": {"rel": "self"}
      }
    }
  ]
}

=== DendraScience/dendra-web-api/test/server/20/data/datastream_ts2008-pref.json
{
  "datapoints_config": [
    {
      "ends_before": "2017-06-02T00:00:00.000Z",
      "params": {
        "query": {
          "ds_id": 1
        }
      },
      "path": "/datavalues-ts2008"
    },
    {
      "begins_at": "2017-06-02T00:00:00.000Z",
      "params": {
        "query": {
          "ds_id": 2
        }
      },
      "path": "/datavalues-ts2008"
    }
  ],
  "derivation_description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.",
  "derived_from_datastream_ids": [
    "592f155746a1b867a114e021"
  ],
  "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.",
  "enabled": true,
  "external_refs": [
    {
      "identifier": "3090",
      "type": "odm.datastreams.datastreamid"
    },
    {
      "identifier": "334",
      "type": "odm.stations.stationid",
      "url": "http://sensor.berkeley.edu/index_ucnrs.html"
    }
  ],
  "geo": {
    "coordinates": [
      -121.73638,
      37.381666,
      574.548
    ],
    "type": "Point"
  },
  "members": [
    {
      "organization_id": "592f155746a1b867a114e030",
      "roles": [
        "contact"
      ]
    },
    {
      "person_id": "592f155746a1b867a114e040",
      "roles": [
        "admin",
        "contact"
      ]
    }
  ],
  "name": "TS2008 Datastream",
  "organization_id": "592f155746a1b867a114e030",
  "preferred_uom_ids": [
    "met2008-centimeter"
  ],
  "source": "science.dendra.test.ts2008",
  "source_type": "sensor",
  "state": "ready",
  "station_id": "592f155746a1b867a114e060",
  "tags": [
    "ts2008_Class_TermA",
    "ts2008_Unit_Meter"
  ],
  "thing_id": "592f155746a1b867a114e070",
  "urls": [
    {
      "label": "Wiki",
      "url": "https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature"
    }
  ]
}

=== DendraScience/dendra-web-api/test/server/20/data/datastream_ts2003.json
{
  "attributes": {
    "height": {
      "unit_tag": "ts2003_Unit_Meter",
      "value": 10
    }
  },
  "datapoints_config": [
    {
      "begins_at": "2017-05-28T09:50:23.106Z",
      "connection": "legacy",
      "ends_before": "2017-05-28T09:50:23.106Z",
      "params": {
        "query": {
          "datastream_id": 3090,
          "time_adjust": -28800
        }
      },
      "path": "/datavalues-ucnrs"
    }
  ],
  "derivation_description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.",
  "derived_from_datastream_ids": [
    "592f155746a1b867a114e021"
  ],
  "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.",
  "enabled": true,
  "external_refs": [
    {
      "identifier": "3090",
      "type": "odm.datastreams.datastreamid"
    },
    {
      "identifier": "334",
      "type": "odm.stations.stationid",
      "url": "http://sensor.berkeley.edu/index_ucnrs.html"
    }
  ],
  "geo": {
    "coordinates": [
      -121.73638,
      37.381666,
      574.548
    ],
    "type": "Point"
  },
  "members": [
    {
      "organization_id": "592f155746a1b867a114e030",
      "roles": [
        "contact"
      ]
    },
    {
      "person_id": "592f155746a1b867a114e040",
      "roles": [
        "admin",
        "contact"
      ]
    }
  ],
  "name": "TS2003 Datastream",
  "organization_id": "592f155746a1b867a114e030",
  "preferred_uom_ids": [
    "imp2003-a"
  ],
  "source": "science.dendra.test.ts2003",
  "source_type": "sensor",
  "state": "ready",
  "station_id": "592f155746a1b867a114e060",
  "tags": [
    "ts2003_Class_TermA",
    "ts2003_Unit_Meter"
  ],
  "thing_id": "592f155746a1b867a114e070",
  "urls": [
    {
      "label": "Wiki",
      "url": "https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature"
    }
  ]
}

=== DendraScience/dendra-web-api/test/server/20/data/datastream_ts2006-c.json
{
  "datapoints_config": [
    {
      "begins_at": "2017-05-28T09:50:23.106Z",
      "connection": "legacy",
      "ends_before": "2017-05-28T09:50:23.106Z",
      "params": {
        "query": {
          "datastream_id": 3090,
          "time_adjust": -28800
        }
      },
      "path": "/datavalues-ucnrs"
    }
  ],
  "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.",
  "enabled": true,
  "name": "TS2006 C Datastream",
  "source": "science.dendra.test.ts2006",
  "source_type": "sensor",
  "state": "ready",
  "station_id": "592f155746a1b867a114e064",
  "tags": [
    "ts2006_Class1_Term1B",
    "ts2006_Class2_Term2B"
  ]
}
