=== DendraScience/dendra-web-api/schema/monitor.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "monitor.json",
  "title": "Monitor",
  "description": "A specification for automated monitoring of resources or system components.",
  "type": "object",
  "definitions": {
    "_id": {
      "$ref": "types.json#/definitions/monitorId"
    },
    "organization_id": {
      "$ref": "types.json#/definitions/organizationId",
      "description": "The organization to which this monitor belongs"
    },
    "spec_type": {
      "description": "The specification type for monitoring",
      "example": "station/status",
      "type": "string"
    },
    "state": {
      "type": "string",
      "description": "The current state of this monitor",
      "example": "finished"
    }
  },
  "additionalProperties": false,
  "properties": {
    "_id": {"$ref": "#/definitions/_id"},
    "created_at": {"$ref": "types.json#/definitions/createdAt"},
    "created_by": {"$ref": "types.json#/definitions/createdBy"},
    "organization_id": {"$ref": "#/definitions/organization_id"},
    "result": {"$ref": "types.json#/definitions/result"},
    "result_pre": {"$ref": "types.json#/definitions/result"},
    "result_post": {"$ref": "types.json#/definitions/result"},
    "spec": {"$ref": "types.json#/definitions/serviceSpec"},
    "spec_type": {"$ref": "#/definitions/spec_type"},
    "state": {"$ref": "#/definitions/state"},
    "updated_at": {"$ref": "types.json#/definitions/updatedAt"},
    "updated_by": {"$ref": "types.json#/definitions/updatedBy"},
    "version_id": {"$ref": "types.json#/definitions/versionId"}
  },
  "required": [
    "spec",
    "spec_type",
    "state"
  ],
  "links": [
    {
      "title": "Create monitor",
      "description": "Create a new monitor.",
      "rel": "self",
      "href": "monitors",
      "method": "POST",
      "schema": {
        "type": "object",
        "properties": {
          "organization_id": {"$ref": "#/definitions/organization_id"},
          "result": {"$ref": "types.json#/definitions/result"},
          "result_pre": {"$ref": "types.json#/definitions/result"},
          "result_post": {"$ref": "types.json#/definitions/result"},
          "spec": {"$ref": "types.json#/definitions/serviceSpec"},
          "spec_type": {"$ref": "#/definitions/spec_type"},
          "state": {"$ref": "#/definitions/state"}
        },
        "required": [
          "spec",
          "spec_type",
          "state"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Patch monitor",
      "description": "Patch an existing monitor.",
      "rel": "self",
      "href": "monitors/{#/definitions/_id}",
      "method": "PATCH",
      "schema": {
        "type": "object",
        "properties": {
          "result": {"$ref": "types.json#/definitions/result"},
          "result_pre": {"$ref": "types.json#/definitions/result"},
          "result_post": {"$ref": "types.json#/definitions/result"},
          "state": {"$ref": "#/definitions/state"}
        }
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Update monitor",
      "description": "Update an existing monitor.",
      "rel": "self",
      "href": "monitors/{#/definitions/_id}",
      "method": "PUT",
      "schema": {
        "type": "object",
        "properties": {
          "_id": {"$ref": "#/definitions/_id"},
          "organization_id": {"$ref": "#/definitions/organization_id"},
          "result": {"$ref": "types.json#/definitions/result"},
          "result_pre": {"$ref": "types.json#/definitions/result"},
          "result_post": {"$ref": "types.json#/definitions/result"},
          "spec": {"$ref": "types.json#/definitions/serviceSpec"},
          "spec_type": {"$ref": "#/definitions/spec_type"},
          "state": {"$ref": "#/definitions/state"}
        },
        "required": [
          "spec",
          "spec_type",
          "state"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Remove monitor",
      "description": "Remove an existing monitor.",
      "rel": "self",
      "href": "monitors/{#/definitions/_id}",
      "method": "DELETE",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Monitor info",
      "description": "Return a specific monitor.",
      "rel": "self",
      "href": "monitors/{#/definitions/_id}",
      "method": "GET",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "List monitors",
      "description": "Find one or more monitors based on the query parameters.",
      "rel": "instances",
      "href": "monitors",
      "method": "GET",
      "schema": {
        "$ref": "types.json#/definitions/queryParameters"
      },
      "targetSchema": {
        "allOf": [
          {"$ref": "types.json#/definitions/paginationMeta"},
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {"rel": "self"}
              }
            }
          }
        ]
      }
    }
  ]
}

=== DendraScience/dendra-web-api/test/data/demo.monitor.update.json
{
  "created_at": "2017-07-21T03:16:36.664Z",
  "created_by": "592f155746a1b867a114e010",
  "organization_id": "592f155746a1b867a114e030",
  "result": {
    "alive": true
  },
  "spec": {
    "comment": "Demo Monitor - Updated",
    "method": "eval"
  },
  "spec_type": "station/status",
  "state": "pending",
  "updated_at": "2017-07-21T03:16:36.664Z",
  "updated_by": "592f155746a1b867a114e010"
}
