=== DendraScience/dendra-web-api/schema/person.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "person.json",
  "title": "Person",
  "description": "A data consumer, responsible party, or user of the system.",
  "type": "object",
  "definitions": {
    "_id": {
      "$ref": "types.json#/definitions/personId"
    },
    "email": {
      "$ref": "types.json#/definitions/email",
      "example": "collin@berkeley.edu"
    },
    "full_name": {
      "type": "string",
      "example": "Collin Bode"
    },
    "name": {
      "type": "string",
      "example": "Collin"
    }
  },
  "additionalProperties": false,
  "properties": {
    "_id": {"$ref": "#/definitions/_id"},
    "created_at": {"$ref": "types.json#/definitions/createdAt"},
    "created_by": {"$ref": "types.json#/definitions/createdBy"},
    "email": {"$ref": "#/definitions/email"},
    "full_name": {"$ref": "#/definitions/full_name"},
    "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
    "name": {"$ref": "#/definitions/name"},
    "updated_at": {"$ref": "types.json#/definitions/updatedAt"},
    "updated_by": {"$ref": "types.json#/definitions/updatedBy"},
    "version_id": {"$ref": "types.json#/definitions/versionId"}
  },
  "required": [
    "is_enabled",
    "name"
  ],
  "links": [
    {
      "title": "Create person",
      "description": "Create a new person.",
      "rel": "self",
      "href": "persons",
      "method": "POST",
      "schema": {
        "type": "object",
        "properties": {
          "email": {"$ref": "#/definitions/email"},
          "full_name": {"$ref": "#/definitions/full_name"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "name": {"$ref": "#/definitions/name"}
        },
        "required": [
          "is_enabled",
          "name"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Patch person",
      "description": "Patch an existing person.",
      "rel": "self",
      "href": "persons/{#/definitions/_id}",
      "method": "PATCH",
      "schema": {
        "type": "object",
        "properties": {
          "email": {"$ref": "#/definitions/email"},
          "full_name": {"$ref": "#/definitions/full_name"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "name": {"$ref": "#/definitions/name"}
        }
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Update person",
      "description": "Update an existing person.",
      "rel": "self",
      "href": "persons/{#/definitions/_id}",
      "method": "PUT",
      "schema": {
        "type": "object",
        "properties": {
          "_id": {"$ref": "#/definitions/_id"},
          "email": {"$ref": "#/definitions/email"},
          "full_name": {"$ref": "#/definitions/full_name"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "name": {"$ref": "#/definitions/name"}
        },
        "required": [
          "is_enabled",
          "name"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Remove person",
      "description": "Remove an existing person.",
      "rel": "self",
      "href": "persons/{#/definitions/_id}",
      "method": "DELETE",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Person info",
      "description": "Return a specific person.",
      "rel": "self",
      "href": "persons/{#/definitions/_id}",
      "method": "GET",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "List persons",
      "description": "Find one or more persons based on the query parameters.",
      "rel": "instances",
      "href": "persons",
      "method": "GET",
      "schema": {
        "$ref": "types.json#/definitions/queryParameters"
      },
      "targetSchema": {
        "allOf": [
          {"$ref": "types.json#/definitions/paginationMeta"},
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {"rel": "self"}
              }
            }
          }
        ]
      }
    }
  ]
}

=== DendraScience/dendra-web-api/test/data/demo.person.update.json
{
  "created_at": "2017-07-21T03:16:36.664Z",
  "created_by": "592f155746a1b867a114e010",
  "email": "demo_person@test.dendra.science",
  "full_name": "Demo Person - Updated",
  "is_enabled": true,
  "name": "Demo Person",
  "updated_at": "2017-07-21T03:16:36.664Z",
  "updated_by": "592f155746a1b867a114e010"
}
