=== DendraScience/dendra-web-api/schema/user.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "user.json",
  "title": "User",
  "description": "A user account with credentials for authentication.",
  "type": "object",
  "definitions": {
    "_id": {
      "$ref": "types.json#/definitions/userId"
    },
    "email": {
      "$ref": "types.json#/definitions/email",
      "example": "collin@berkeley.edu"
    },
    "full_name": {
      "type": "string",
      "example": "Collin Bode"
    },
    "name": {
      "type": "string",
      "example": "Collin"
    },
    "password": {
      "type": "string",
      "description": "A password for local authentication"
    },
    "person_id": {
      "$ref": "types.json#/definitions/personId",
      "description": "The person affiliated with this user account"
    },
    "roles": {
      "type": "array",
      "description": "The user's roles within the system (e.g. 'sys-admin')",
      "maxItems": 1,
      "minItems": 1,
      "items": {
        "type": "string",
        "example": "sys-admin"
      }
    }
  },
  "additionalProperties": false,
  "properties": {
    "_id": {"$ref": "#/definitions/_id"},
    "created_at": {"$ref": "types.json#/definitions/createdAt"},
    "created_by": {"$ref": "types.json#/definitions/createdBy"},
    "email": {"$ref": "#/definitions/email"},
    "full_name": {"$ref": "#/definitions/full_name"},
    "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
    "name": {"$ref": "#/definitions/name"},
    "password": {"$ref": "#/definitions/password"},
    "person_id": {"$ref": "#/definitions/person_id"},
    "roles": {"$ref": "#/definitions/roles"},
    "updated_at": {"$ref": "types.json#/definitions/updatedAt"},
    "updated_by": {"$ref": "types.json#/definitions/updatedBy"}
  },
  "required": [
    "email",
    "is_enabled",
    "name",
    "password",
    "roles"
  ],
  "links": [
    {
      "title": "Create user",
      "description": "Create a new user.",
      "rel": "self",
      "href": "users",
      "method": "POST",
      "schema": {
        "type": "object",
        "properties": {
          "email": {"$ref": "#/definitions/email"},
          "full_name": {"$ref": "#/definitions/full_name"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "name": {"$ref": "#/definitions/name"},
          "password": {"$ref": "#/definitions/password"},
          "person_id": {"$ref": "#/definitions/person_id"},
          "roles": {"$ref": "#/definitions/roles"}
        },
        "required": [
          "email",
          "is_enabled",
          "name",
          "password",
          "roles"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Patch user",
      "description": "Patch an existing user.",
      "rel": "self",
      "href": "users/{#/definitions/_id}",
      "method": "PATCH",
      "schema": {
        "type": "object",
        "properties": {
          "email": {"$ref": "#/definitions/email"},
          "full_name": {"$ref": "#/definitions/full_name"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "name": {"$ref": "#/definitions/name"},
          "password": {"$ref": "#/definitions/password"},
          "person_id": {"$ref": "#/definitions/person_id"},
          "roles": {"$ref": "#/definitions/roles"}
        }
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Update user",
      "description": "Update an existing user.",
      "rel": "self",
      "href": "users/{#/definitions/_id}",
      "method": "PUT",
      "schema": {
        "type": "object",
        "properties": {
          "_id": {"$ref": "#/definitions/_id"},
          "email": {"$ref": "#/definitions/email"},
          "full_name": {"$ref": "#/definitions/full_name"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "name": {"$ref": "#/definitions/name"},
          "password": {"$ref": "#/definitions/password"},
          "person_id": {"$ref": "#/definitions/person_id"},
          "roles": {"$ref": "#/definitions/roles"}
        },
        "required": [
          "email",
          "is_enabled",
          "name",
          "password",
          "roles"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Remove user",
      "description": "Remove an existing user.",
      "rel": "self",
      "href": "users/{#/definitions/_id}",
      "method": "DELETE",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "User info",
      "description": "Return a specific user.",
      "rel": "self",
      "href": "users/{#/definitions/_id}",
      "method": "GET",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "List users",
      "description": "Find one or more users based on the query parameters.",
      "rel": "instances",
      "href": "users",
      "method": "GET",
      "schema": {
        "$ref": "types.json#/definitions/queryParameters"
      },
      "targetSchema": {
        "allOf": [
          {"$ref": "types.json#/definitions/paginationMeta"},
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {"rel": "self"}
              }
            }
          }
        ]
      }
    }
  ]
}

=== DendraScience/dendra-web-api/test/data/demo-user.user.update.json
{
  "created_at": "2017-07-21T03:16:36.664Z",
  "created_by": "592f155746a1b867a114e010",
  "email": "demo_user@test.dendra.science",
  "full_name": "Demo User - Updated",
  "is_enabled": true,
  "name": "Demo User",
  "password": "test123",
  "person_id": "592f155746a1b867a114e040",
  "roles": [
    "user"
  ],
  "updated_at": "2017-07-21T03:16:36.664Z",
  "updated_by": "592f155746a1b867a114e010"
}

=== DendraScience/dendra-web-api/test/data/sample-user.user.update.json
{
  "created_at": "2017-07-21T03:16:36.664Z",
  "created_by": "592f155746a1b867a114e010",
  "email": "sample_user@test.dendra.science",
  "full_name": "Test User - Updated",
  "is_enabled": true,
  "name": "Sample User Role",
  "password": "test123",
  "roles": [
    "user"
  ],
  "updated_at": "2017-07-21T03:16:36.664Z",
  "updated_by": "592f155746a1b867a114e010"
}
