=== DendraScience/dendra-web-api/schema/vocabulary.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "vocabulary.json",
  "title": "Vocabulary",
  "description": "A controlled vocabulary used to tag data producing entities.",
  "type": "object",
  "definitions": {
    "_id": {
      "$ref": "types.json#/definitions/vocabularyId"
    },
    "description": {
      "$ref": "types.json#/definitions/description",
      "example": "Terms describing how multiple values are grouped together to form a single value."
    },
    "label": {
      "$ref": "types.json#/definitions/label",
      "example": "Aggregate"
    },
    "scheme_id": {
      "$ref": "types.json#/definitions/schemeId",
      "description": "The scheme to which this vocabulary belongs"
    },
    "term": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "abbreviation": {
          "type": "string",
          "example": "avg"
        },
        "definition": {
          "type": "string",
          "example": "The sum of a collection of numbers divided by the number of numbers in the collection."
        },
        "label": {
          "$ref": "types.json#/definitions/label",
          "example": "Average"
        },
        "name": {
          "type": "string",
          "example": "Average/Mean"
        }
      },
      "required": [
        "label"
      ]
    },
    "terms": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/term"
      }
    },
    "vocabulary_type": {
      "type": "string",
      "description": "Whether the vocabulary is a general purpose classifier or describes a unit of measurement",
      "example": "class",
      "enum": ["class", "unit"]
    }
  },
  "additionalProperties": false,
  "properties": {
    "_id": {"$ref": "#/definitions/_id"},
    "created_at": {"$ref": "types.json#/definitions/createdAt"},
    "created_by": {"$ref": "types.json#/definitions/createdBy"},
    "description": {"$ref": "#/definitions/description"},
    "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
    "is_hidden": {"$ref": "types.json#/definitions/isHidden"},
    "label": {"$ref": "#/definitions/label"},
    "scheme_id": {"$ref": "#/definitions/scheme_id"},
    "terms": {"$ref": "#/definitions/terms"},
    "updated_at": {"$ref": "types.json#/definitions/updatedAt"},
    "updated_by": {"$ref": "types.json#/definitions/updatedBy"},
    "version_id": {"$ref": "types.json#/definitions/versionId"},
    "vocabulary_type": {"$ref": "#/definitions/vocabulary_type"}
  },
  "required": [
    "_id",
    "is_enabled",
    "is_hidden",
    "label",
    "scheme_id",
    "vocabulary_type"
  ],
  "links": [
    {
      "title": "Create vocabulary",
      "description": "Create a new vocabulary.",
      "rel": "self",
      "href": "vocabularies",
      "method": "POST",
      "schema": {
        "type": "object",
        "properties": {
          "_id": {"$ref": "#/definitions/_id"},
          "description": {"$ref": "#/definitions/description"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "is_hidden": {"$ref": "types.json#/definitions/isHidden"},
          "label": {"$ref": "#/definitions/label"},
          "scheme_id": {"$ref": "#/definitions/scheme_id"},
          "terms": {"$ref": "#/definitions/terms"},
          "vocabulary_type": {"$ref": "#/definitions/vocabulary_type"}
        },
        "required": [
          "_id",
          "is_enabled",
          "is_hidden",
          "label",
          "scheme_id",
          "vocabulary_type"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Patch vocabulary",
      "description": "Patch an existing vocabulary.",
      "rel": "self",
      "href": "vocabularies/{#/definitions/_id}",
      "method": "PATCH",
      "schema": {
        "type": "object",
        "properties": {
          "description": {"$ref": "#/definitions/description"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "is_hidden": {"$ref": "types.json#/definitions/isHidden"},
          "label": {"$ref": "#/definitions/label"},
          "terms": {"$ref": "#/definitions/terms"},
          "vocabulary_type": {"$ref": "#/definitions/vocabulary_type"}
        }
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Update vocabulary",
      "description": "Update an existing vocabulary.",
      "rel": "self",
      "href": "vocabularies/{#/definitions/_id}",
      "method": "PUT",
      "schema": {
        "type": "object",
        "properties": {
          "_id": {"$ref": "#/definitions/_id"},
          "description": {"$ref": "#/definitions/description"},
          "is_enabled": {"$ref": "types.json#/definitions/isEnabled"},
          "is_hidden": {"$ref": "types.json#/definitions/isHidden"},
          "label": {"$ref": "#/definitions/label"},
          "scheme_id": {"$ref": "#/definitions/scheme_id"},
          "terms": {"$ref": "#/definitions/terms"},
          "vocabulary_type": {"$ref": "#/definitions/vocabulary_type"}
        },
        "required": [
          "_id",
          "is_enabled",
          "is_hidden",
          "label",
          "scheme_id",
          "vocabulary_type"
        ]
      },
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Remove vocabulary",
      "description": "Remove an existing vocabulary.",
      "rel": "self",
      "href": "vocabularies/{#/definitions/_id}",
      "method": "DELETE",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "Vocabulary info",
      "description": "Return a specific vocabulary.",
      "rel": "self",
      "href": "vocabularies/{#/definitions/_id}",
      "method": "GET",
      "targetSchema": {"rel": "self"}
    },
    {
      "title": "List vocabularies",
      "description": "Find one or more vocabularies based on the query parameters.",
      "rel": "instances",
      "href": "vocabularies",
      "method": "GET",
      "schema": {
        "$ref": "types.json#/definitions/queryParameters"
      },
      "targetSchema": {
        "allOf": [
          {"$ref": "types.json#/definitions/paginationMeta"},
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {"rel": "self"}
              }
            }
          }
        ]
      }
    }
  ]
}

=== DendraScience/dendra-web-api/test/data/ds-medium.vocabulary.json
{
  "_id": "ds-medium",
  "is_enabled": true,
  "is_hidden": false,
  "label": "Medium",
  "scheme_id": "ds",
  "terms": [
    {
      "label": "Air"
    },
    {
      "label": "Battery"
    },
    {
      "label": "GroundWater",
      "name": "Ground Water"
    },
    {
      "label": "Instrument"
    },
    {
      "label": "Leaf"
    },
    {
      "label": "Not Applicable",
      "name": "NotApplicable"
    },
    {
      "label": "Precipitation"
    },
    {
      "label": "Rock"
    },
    {
      "label": "Sap"
    },
    {
      "label": "Saprolite"
    },
    {
      "label": "Sediment"
    },
    {
      "label": "Sky"
    },
    {
      "label": "Snow"
    },
    {
      "label": "Soil"
    },
    {
      "label": "Solar"
    },
    {
      "label": "SurfaceWater",
      "name": "Surface Water"
    },
    {
      "label": "Tissue"
    },
    {
      "label": "Unknown"
    },
    {
      "label": "Water"
    }
  ],
  "vocabulary_type": "class"
}

=== DendraScience/dendra-web-api/test/data/ds-variable.vocabulary.update.json
{
  "_id": "ds-variable",
  "created_at": "2017-05-28T09:50:23.106Z",
  "created_by": "592f155746a1b867a114e010",
  "is_enabled": true,
  "is_hidden": false,
  "label": "Variable - Updated",
  "scheme_id": "ds",
  "terms": [
    {
      "label": "BarometricPressure",
      "name": "Barometric Pressure"
    },
    {
      "label": "Concentration"
    },
    {
      "label": "Count"
    },
    {
      "label": "Depth"
    },
    {
      "label": "Description"
    },
    {
      "label": "DielectricStrength",
      "name": "Dielectric Strength"
    },
    {
      "label": "Direction"
    },
    {
      "label": "Discharge"
    },
    {
      "label": "Duration"
    },
    {
      "label": "ElectricCurrent",
      "name": "Electric Current"
    },
    {
      "label": "ElectricalResistance",
      "name": "Electrical Resistance"
    },
    {
      "label": "ElectricalConductivity",
      "name": "Electrical Conductivity"
    },
    {
      "label": "Evapotranspiration"
    },
    {
      "label": "Flux"
    },
    {
      "label": "Height"
    },
    {
      "label": "Luminance"
    },
    {
      "label": "Moisture"
    },
    {
      "label": "NetRadiation",
      "name": "Net Radiation"
    },
    {
      "label": "Period"
    },
    {
      "label": "PhotosyntheticallyActiveRadiation",
      "name": "Photosynthetically Active Radiation"
    },
    {
      "label": "Power"
    },
    {
      "label": "Precipitation"
    },
    {
      "label": "Pressure"
    },
    {
      "label": "RelativeHumidity",
      "name": "Relative Humidity"
    },
    {
      "label": "Radiation"
    },
    {
      "label": "RadioTransmission",
      "name": "Radio Transmission"
    },
    {
      "label": "Speed"
    },
    {
      "label": "Temperature"
    },
    {
      "label": "Transpiration"
    },
    {
      "label": "Turbidity"
    },
    {
      "label": "Unknown"
    },
    {
      "label": "VaporPressure",
      "name": "Vapor Pressure"
    },
    {
      "label": "VaporPressureDeficit",
      "name": "Vapor Pressure Deficit"
    },
    {
      "label": "Velocity"
    },
    {
      "label": "Visibility"
    },
    {
      "label": "Voltage"
    },
    {
      "label": "Volume"
    },
    {
      "label": "VolumetricWaterContent",
      "name": "Volumetric Water Content"
    }
  ],
  "updated_at": "2017-05-28T09:50:23.106Z",
  "updated_by": "592f155746a1b867a114e010",
  "vocabulary_type": "class"
}

=== DendraScience/dendra-web-api/test/data/ds-aggregate.vocabulary.json
{
  "_id": "ds-aggregate",
  "is_enabled": true,
  "is_hidden": false,
  "label": "Aggregate",
  "scheme_id": "ds",
  "terms": [
    {
      "label": "Average",
      "name": "Average/Mean"
    },
    {
      "label": "Maximum"
    },
    {
      "label": "Median"
    },
    {
      "label": "Minimum"
    },
    {
      "label": "StandardDeviation",
      "name": "Standard Deviation"
    },
    {
      "label": "Cumulative"
    }
  ],
  "vocabulary_type": "class"
}
